### ISSUE TITLE
GPU support 

### ISSUE THREAD

**Issue by OOKAMIFR** [phulshof/RetroFE#2]
Hello
First of all, thanks for your work :)
I successfully compiled for the Raspberry Pi 3 (32 & 64bits) and noticed Front-end seems to be not managed by the GPU
Even with my poor knowledge, I took a look and saw Front-end is not compiled with OpenGL support 

Any chance to implement GPU support for a better improvement?

Hope my request is not idiot and again, thanks for amazing work of this Front-end :)

**Comment by phulshof** [comment]
Make sure you use the hardware accelerated SDL library; RetroFE uses that for all its display.
