### ISSUE TITLE
MP4 Media When Launching/Playing Games?

### ISSUE THREAD

**Issue by natemac** [phulshof/RetroFE#6]
This is a feature request rather then an issue...
Is it possible to launch a video/mp4 file when a game launches for an "animated" marquee?

Currently when a game launches It load a jpg on a secondary monitor to show the marquee while playing.
I would like to load a mp4 that continues to play/loop while playing, till the game is exited.
Attached is an example of the feature, the lower right monitor. https://youtu.be/UT3bLyM7HQY?t=251

**Comment by phulshof** [comment]
When a game is launched, RetroFE stops actively updating the screen since it remains dormant until the game returns control back over to RetroFE. Running an animated marquee is therefore not an option at this time.
